# Diff Drive Controller ---------------------------------------
velocity_controller:
   type: "diff_drive_controller/DiffDriveController"
   left_wheel: ['fl_wheel_joint', 'rl_wheel_joint']
   right_wheel: ['fr_wheel_joint', 'rr_wheel_joint']
   publish_rate: 100
   pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
   twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
   cmd_vel_timeout: 0.25
   
   # Base frame_id
   base_frame_id: base_link
   
   # Odometry fused with IMU, so no
   # need to publish a TF based on encoders alone.
   enable_odom_tf: false
   
   # a390 hardware provides wheel velocities
   estimate_velocity_from_position: false
   
   wheel_radius : 0.05 # 0.0675 #0.064
   wheel_separation : 0.365

   # Wheel separation and radius multipliers
   wheel_separation_multiplier: 1.5 # default: 1.0 ajuster pour qu il tourne de la bonne quantite
   wheel_radius_multiplier : 1.0 # default: 1.0 a modifier pour la distance la ligne droite
   
   # Velocity and acceleration limits
   # Whenever a min_* is unspecified, default to -max_*
   linear:
      x:
        has_velocity_limits : true
        max_velocity        : 0.450 # m/s
        min_velocity        : -0.450 # m/s
        has_acceleration_limits: true
        max_acceleration    : 1.500 # m/s^2
        min_acceleration    : -1.500 # m/s^2
   angular:
      z:
        has_velocity_limits : true
        max_velocity        : 1.0 # rad/s
        has_acceleration_limits: true
        max_acceleration     : 3.0 # rad/s^2