footprint: [[-0.45, -0.5], [-0.45, 0.5], [0.45, 0.5], [0.475, 0.0], [0.45, -0.5]]
footprint_padding: 0.01
inflation_radius: 1.0

robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 19.5
raytrace_range: 20.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: laser/scan, inf_is_valid: true}
    #laser: {data_type: PointCloud2, clearing: true, marking: true, topic: rslidar_points, inf_is_valid: true}

